# Generated by Django 4.0.6 on 2022-07-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todolist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
